name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  gh-pages-deploy:
    name: Deploying to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.4.4
        with:
          version: 10.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Install bower
        run: |
         set -x
         node -v
         npm install -g bower
         bower install
       
      - name: Build Application
        run: npx ember build

      - name: Commit files
        run: |
          git config --local user.email "siriusiii1209@gmail.com"
          git config --local user.name "NurgalievAl"
          echo "Start to deploy..."

          git checkout --orphan gh-pages
          ls -l
          
          git --work-tree ./dist add --all
          git --work-tree ./dist commit -m "Deploy to GitHub Pages"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
      - name: Remove branch
        run: |
          rm -r dist

          git checkout -f main
          git branch -D gh-pages

          echo "Successfully deployed"
